#端口
server:
  port:9999
#数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/health?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  main:
    allow-bean-definition-overriding: true

  redis:
    port:6379
    host:localhost

file:
  upload-dir: E:/uploads/recipe-images/
  access-path: /recipe-images/
  max-image-size: 10MB                      # 图片大小限制
  allowed-image-types: image/jpeg,image/png # 允许的图片类型

#debug报告
logging:
  level:
    com.jyx: debug

#逻辑删除
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  type-aliases-package: com.jyx.*.entity




